FROM centos:7

# ffmpeg
RUN yum -y localinstall --nogpgcheck https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-7.noarch.rpm https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-7.noarch.rpm
RUN yum -y install ffmpeg

# PostgresSQL
RUN yum -y install postgresql-libs

# Other
RUN yum -y install -y npm
RUN yum -y install -y cronie

# python
RUN yum -y install python3-pip

# location where static is generated (on runtime - using django collectstatic)
VOLUME /app/collected_static

# install npm pkgs
# location is in '/npm_static' (one of the locations where django collectstatic search for statics)
WORKDIR /npm_static
COPY ./static/package.json ./
RUN npm install

# install backend python requirements
WORKDIR /app
COPY ./requirements.txt ./
RUN pip3 install -r requirements.txt

# setup cronjob
COPY cronjob /etc/cron.d/cronjob
RUN chmod 0644 /etc/cron.d/cronjob
RUN crontab /etc/cron.d/cronjob
RUN touch /var/log/cron.log
